services:
  postgres:
    image: postgres:15
    container_name: pg_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: Divyansh
      POSTGRES_PASSWORD: dabadebadeba
      POSTGRES_DB: info_now_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    depends_on:
      - postgres
    environment:
      DB_USER: Divyansh
      DB_PASSWORD: dabadebadeba
      DB_HOST: postgres
      DB_NAME: info_now_db
      DB_PORT: 5432
      AUTH_TYPE: plain
      POOL_MODE: session
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 20
    ports:
      - "6432:5432"

  redis:
    image: redis:alpine
    container_name: redis-name
    restart: unless-stopped
    command: ["redis-server"]
    volumes:
      - redis_data:/data

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/var/lib/kafka/data

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: os-main
    environment:
      - cluster.name=dev-cluster
      - node.name=os-main
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - plugins.security.disabled=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ports:
      - "9200:9200"
      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cat/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch_dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0 # Match the version above
    container_name: os-dash
    depends_on:
      opensearch:
        condition: service_healthy # Wait for the healthcheck above
    environment:
      OPENSEARCH_HOSTS: '["http://os-main:9200"]' # Use container_name or service name
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    ports:
      - "5601:5601"

volumes:
  postgres_data:
  redis_data:
  kafka_data:
  opensearch_data:
